[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/soumitrachakravarti/an-introduction-to-tensorflow/blob/main/01-Basics.ipynb)

## Basics

### What is TensorFlow?

TensorFlow is an end-to-end platform that makes it easy for you to build and deploy machine learning models. It is an open-source library for preprocessing data, modelling data and serving machine learning models

### Why do we use TensorFlow?
It's the same reason why use any library; to make life easier and quicker and not try to reinvent the wheel. Meaning, rather than building machine learning and deep learning models from the ground up, it's more efficient to use a library such as TensorFlow as it contains many common machine learning functions for easy implentation.

### Objectives
TF (TensorFlow) is enormous and vast, but the key idea is to convert data into numbers (referred as tensors) and use ML to identify patterns, which sounds fairly simple and it sometimes is but can very quickly become more complex.

In this tutorial series for TF, we will cover fundamental operations like:
* Tensors, their attributes and operations
* NumPy (another python library)
* Performance and GPU implemntation
* [TF Documentation](https://www.tensorflow.org/api_docs/python/tf)

### Tensors
Tensors are n-dimensional [arrays](https://www.freecodecamp.org/news/python-array-tutorial-define-index-methods/), where n can be any number of:
* numbers; tensors used to represent the daily prices of a mangoes 
* images; tenors used to represent the pixels of images of different types of mangoes
* text; tensors used to represent words about how much people like or dislike eating mangoes
* tensors can be used to represent any form of information

### NumPy
[NumPy](https://numpy.org/doc/stable/) is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

### What's the difference?
NumPy Arrays can run on CPU while Tensors can also run on **GPU** (and TPU), which results in faster performance; meaning less time


In [ ]:
# Hands On
import tensorflow as tf
# Sample Output 2.9.2
print(tf.__version__)

### Creating your first Tensor
In the real world, you would not be creating tensors manually, you would want to read from a data source and TF will automatically convert them to tensors.

But just for our learning, we will create one manually using [tf.constant()](https://www.tensorflow.org/api_docs/python/tf/constant)

In [ ]:
# Let's create the most simplest form of a tensor, Scalar
# Scalar is a tensor with no dimensions, or simply just a number
# Scalar is of a rank 0

# Creating a scalar
scalar = tf.constant(5) # You can use any other number than 5

# Type check scalar
# Sample Output <tf.Tensor: shape=(), dtype=int32, numpy=5>
scalar

In [ ]:
# Check tensor dimensions using ndim
# Sample Output 0
scalar.ndim

In [ ]:
# tf.constant() can be used to create tensors with more dimensions
# A tensor with dimension 1 is called a vector
vector = tf.constant([5, 5])

# Type check vector
# Sample Output <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>
vector

In [ ]:
# Check tensor dimensions using ndim
# Sample Output 1
vector.ndim

TF creates tensors with 32 bit precision by default. Meaning it either creates tensors using an int32 datatype or a float32 datatype
We have seen so far 2 tensors with 0 and 1 dimensions using int32 data types, which is teh default choice.
Let's now try and create a tensor with not the default settings

In [ ]:
# A tensor with dimension 2 is called a matrix
matrix = tf.constant([[11.5, 5.2], [6.2, 2.8], [5.0, 8.9]], dtype=tf.float16)

# Type check matrix
# Sample Output 
# <tf.Tensor: shape=(3, 2), 
# dtype=float16, 
# numpy=array([[11.5,  5.2],[ 6.2,  2.8],[ 5. ,  8.9]], 
# dtype=float16)>

matrix

In [ ]:
# We can also check the dimensions of matrix using ndim
# Sample Output 2
matrix.ndim

In [ ]:
# Let's create a tensor with 3 dimensions
tensor = tf.constant(
                        # Tabbed for clear reading only
                        [[[10, 22, 3],[42, 45, 76]],
                        [[67, 85, 59],[10, 51, 22]],
                        [[33, 54, 75],[16, 57, 98]]]
                    )

# Type check tensor
# Sample Output
# <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
# array([[[10, 22,  3],
#         [42, 45, 76]],
#        [[67, 85, 59],
#         [10, 51, 22]],
#        [[33, 54, 75],
#         [16, 57, 98]]], dtype=int32)>

tensor

In [ ]:
# Just like before we can also check the dimensions of matrix using ndim
# Sample Output 3
tensor.ndim

The last tensor we created has 3 dimensions and is also know as a rank 3 tensor.
By now you would have clearly guessed that we can create a tensor with any arbitary rank (any dimensions)

Another example can be representing images with a shape of [0, 1, 2, 3]:
* 0 and 1 can be used to represent the size of the image
* 2 can be used to represent color profile like RGB
* 3 can be used to represent the batch size for building neural networks

In [ ]:
# Example tensor representing images
image_tensor = tf.constant([1280, 720, 3, 32])

# Type check image_tensor
# Sample Output
# <tf.Tensor: shape=(4,), dtype=int32,
# numpy=array([1280,  720,    3,   32], dtype=int32)>

image_tensor

In [ ]:
# We can also check the dimensions
# Sample Output 1
image_tensor.ndim

Until now we have created tensors using [tf.constant()](https://www.tensorflow.org/api_docs/python/tf/constant), which most likely you aren't going to use in a real world situation. An important point to note that all the tensors created so far are immutable (meaning can't be changed or constants).
We can use [tf.Variable()](https://www.tensorflow.org/api_docs/python/tf/Variable) exactly the same way. I will leave that as a simple exercise (optional) as most likely TF will automatically choose when you load data as we will see in the upcoming chapters.